#EDGE - CHROME
BROWSER_TYPE=EDGE

#https://rainy.nasam.net/auth/login
ISLOGIN=TRUE
BASE_WEB=https://rainy.nasam.net/auth/login
USERNAME=jeddah
PASSWORD=12345678
userNameLocator=cssSelector:input[placeholder='Username']
passwordLocator=cssSelector:input[placeholder='Password']
clickLocator=cssSelector:button[type='submit']


#LOCAL - HEADLESS - REMOTE
EXECUTION_TYPE=LOCAL

#MODEL API KEY
GEMINI_API_KEY=AIzaSyAOkfcGgIXNOU8BrN3ufbIvifH7KBxvboI
#free model->gemini-3-flash-preview
GEMINI_MODEL=gemini-2.5-flash





#html max chars
HTML_MAX_CHARS=30000

DEFAULT_WAIT=5

DEFAULT_SCREENSHOT_WAIT=1

MaxSteps=10

#Test rainy site dashboard to create new dashboard with name 'dash test'
SCENARIO=Test rainy website to add new dashboard named 'test dashboard' 


