package delivery.codegen;

import delivery.job.TcOutcome;
import delivery.job.TcStatus;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Writes {@code docs/DOMAIN_CATALOG.md} describing generated pages and tests for the customer ZIP.
 */
public final class DomainCatalogWriter {
    private DomainCatalogWriter() {
    }

    public static void write(Path projectRoot, List<TcOutcome> outcomes) throws IOException {
        if (projectRoot == null) {
            throw new IllegalArgumentException("projectRoot is required");
        }
        List<TcOutcome> list = outcomes == null ? List.of() : outcomes;
        PageAccumulator pages = new PageAccumulator();
        for (TcOutcome outcome : list) {
            if (outcome.provenSteps() != null) {
                pages.addAll(outcome.provenSteps());
            }
            if (outcome.needsLoginBeforeMethod() && outcome.loginSteps() != null) {
                pages.addAll(outcome.loginSteps());
            }
        }

        StringBuilder md = new StringBuilder();
        md.append("# Domain catalog (this delivery)\n\n");
        md.append("Generated by Keel for **this** package. Use it to understand which page objects ");
        md.append("and tests were produced from your Excel cases.\n\n");

        md.append("## Pages\n\n");
        md.append("| Page class | Role | Key actions / asserts |\n");
        md.append("|------------|------|------------------------|\n");
        if (pages.pages().isEmpty()) {
            md.append("| — | No pages generated | — |\n");
        } else {
            for (Map.Entry<String, PageAccumulator.PageModel> e : pages.pages().entrySet()) {
                PageAccumulator.PageModel page = e.getValue();
                String role = roleForStem(page.stem());
                String keys = summarizeMethods(page);
                md.append("| `").append(page.actionsClassName()).append("` | ")
                        .append(escapeCell(role)).append(" | ")
                        .append(escapeCell(keys)).append(" |\n");
            }
        }

        md.append("\n## Tests\n\n");
        md.append("| Test class | TC | Status | Title / flow |\n");
        md.append("|------------|----|--------|--------------|\n");
        if (list.isEmpty()) {
            md.append("| — | — | — | No tests generated |\n");
        } else {
            for (TcOutcome o : list) {
                boolean passed = o.status() == TcStatus.PASSED;
                String className = CodegenNaming.testClassName(o.tcId(), passed);
                String flow = pagesUsed(o);
                String title = o.title() == null || o.title().isBlank() ? flow : o.title() + " — " + flow;
                md.append("| `").append(className).append("` | `").append(o.tcId()).append("` | ")
                        .append(o.status()).append(" | ")
                        .append(escapeCell(title)).append(" |\n");
            }
        }

        md.append("\n## How to run\n\n");
        md.append("```bash\n");
        md.append("mvn clean test\n");
        md.append("```\n\n");
        md.append("Configure `BASE_WEB` / credentials via `src/main/resources/webapp.properties` ");
        md.append("(copy from `webapp.properties.example`). See also `docs/AUTOMATION_SCORE.md`.\n");

        Path docs = projectRoot.resolve("docs");
        Files.createDirectories(docs);
        Files.writeString(docs.resolve("DOMAIN_CATALOG.md"), md.toString(), StandardCharsets.UTF_8);
    }

    static String roleForStem(String stem) {
        if (stem == null || stem.isBlank()) {
            return "Application page";
        }
        String s = stem.toLowerCase(Locale.ROOT);
        if (s.contains("login") || s.equals("saucedemo")) {
            return "Login / entry";
        }
        if (s.contains("inventory") || s.contains("product") || s.contains("catalog")) {
            return "Product list";
        }
        if (s.contains("cart")) {
            return "Shopping cart";
        }
        if (s.contains("checkout") && s.contains("complete")) {
            return "Checkout complete";
        }
        if (s.contains("checkout") && (s.contains("two") || s.contains("overview"))) {
            return "Checkout overview";
        }
        if (s.contains("checkout")) {
            return "Checkout form";
        }
        return "Application page (" + stem + ")";
    }

    private static String summarizeMethods(PageAccumulator.PageModel page) {
        List<String> parts = new ArrayList<>();
        for (PageAccumulator.MethodModel m : page.methods()) {
            parts.add(m.name());
            if (parts.size() >= 6) {
                break;
            }
        }
        for (PageAccumulator.AssertionModel a : page.assertions()) {
            if (parts.size() >= 8) {
                break;
            }
            parts.add(a.name());
        }
        if (parts.isEmpty()) {
            return "—";
        }
        String joined = String.join(", ", parts);
        if (page.methods().size() + page.assertions().size() > parts.size()) {
            joined += ", …";
        }
        return joined;
    }

    private static String pagesUsed(TcOutcome o) {
        Set<String> names = new LinkedHashSet<>();
        appendPageNames(names, o.loginSteps());
        appendPageNames(names, o.provenSteps());
        if (names.isEmpty()) {
            return "—";
        }
        return names.stream().map(CodegenNaming::pageStem).collect(Collectors.joining(" → "));
    }

    private static void appendPageNames(Set<String> names, List<ProvenStep> steps) {
        if (steps == null) {
            return;
        }
        for (ProvenStep step : steps) {
            if (step.pageName() != null && !step.pageName().isBlank()) {
                names.add(step.pageName());
            }
        }
    }

    private static String escapeCell(String raw) {
        if (raw == null || raw.isBlank()) {
            return "—";
        }
        return raw.replace("|", "/").replace("\n", " ").trim();
    }
}
