package delivery.codegen;

import delivery.job.TcOutcome;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Writes invented / Excel form values into {@code src/test/resources/test-data/delivery-testdata.properties}
 * so generated tests do not hardcode PII literals.
 */
public final class TestDataPropertiesWriter {
    private TestDataPropertiesWriter() {
    }

    public static void write(Path projectRoot, List<TcOutcome> outcomes) throws IOException {
        if (projectRoot == null || outcomes == null) {
            return;
        }
        Map<String, String> props = new LinkedHashMap<>();
        for (TcOutcome outcome : outcomes) {
            collect(props, outcome.tcId(), outcome.provenSteps());
            if (outcome.needsLoginBeforeMethod()) {
                collect(props, outcome.tcId(), outcome.loginSteps());
            }
        }
        if (props.isEmpty()) {
            return;
        }
        Path dir = projectRoot.resolve("src/test/resources/test-data");
        Files.createDirectories(dir);
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by Keel - edit values here; tests load via PropertyReader\n");
        for (Map.Entry<String, String> e : props.entrySet()) {
            sb.append(e.getKey()).append('=').append(escape(e.getValue())).append('\n');
        }
        Files.writeString(dir.resolve("delivery-testdata.properties"), sb.toString(), StandardCharsets.UTF_8);
    }

    private static void collect(Map<String, String> props, String tcId, List<ProvenStep> steps) {
        if (steps == null) {
            return;
        }
        for (ProvenStep step : steps) {
            String action = step.action() == null ? "" : step.action().toLowerCase(Locale.ROOT);
            if (!"type".equals(action) && !"select".equals(action)) {
                continue;
            }
            String value = step.value() == null ? "" : step.value();
            String key = CodeWriter.propKeyFor(tcId, PageAccumulator.actionMethodName(step), value);
            if (key.isBlank() || "TARGET_USERNAME".equals(key) || "TARGET_PASSWORD".equals(key)) {
                continue;
            }
            if (value.startsWith("${")) {
                continue;
            }
            props.putIfAbsent(key, value);
        }
    }

    private static String escape(String value) {
        if (value == null) {
            return "";
        }
        return value.replace("\\", "\\\\").replace("\n", "\\n");
    }
}
